services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios
    ports:
      - "3307:3306"
    volumes:
      - sgu-volume:/var/lib/mysql
    networks:
      - sgu-net

  frontend:
    build:
      context: ./client
    image: client:1.0-sgu
    container_name: sgu-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - sgu-net
    environment:
      VITE_API_HOST: sgu-backend
      VITE_API_BASE: /usuarios
      VITE_API_PORT: 8081

  backend:
    build:
      context: ./server
    image: server:1.0-sgu
    container_name: sgu-backend
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: usuarios
      DB_USER: root
      DB_PASS: root
    ports:
      - "8081:8080"
    networks:
      - sgu-net
    depends_on:
      - database

volumes:
  sgu-volume:
    external: true

networks:
  sgu-net:
    external: true
